name: CI

on:
  pull_request:
    branches:
    - v2

jobs:
  preview-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - uses: actions/github-script@v5
    - name: install dependencies
      run: npm i
    - name: publish preview version
      run: echo 'Not ready yet'
      # run: npx tsm scripts/run_publish.ts
